name: 功能请求
description: 建议新功能或改进
title: "[功能] "
labels: ["enhancement", "待讨论"]
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢你的建议！

        我们欢迎任何能让 ESAP 变得更好的想法。

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      description: 这个功能属于哪个类别？
      options:
        - 新页面/模块
        - UI/UX 改进
        - 性能优化
        - 新的角色功能
        - 数据/内容相关
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 你想解决什么问题？
      description: 描述当前的不足或需求
      placeholder: 目前在...的时候很不方便，因为...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 你期望的解决方案
      description: 详细描述你希望添加的功能
      placeholder: 我希望能够...，这样就可以...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你考虑过的其他解决方案
      placeholder: 也可以通过...来实现，但是...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: 参考示例
      description: 其他网站/项目的类似功能
      placeholder: 例如 xxx 网站的 xxx 功能...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 你认为这个功能的优先级如何？
      options:
        - 高 - 非常需要
        - 中 - 有会更好
        - 低 - 可有可无
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      description: 你是否愿意帮助实现这个功能？
      options:
        - label: 我愿意提交 PR 来实现这个功能
          required: false
        - label: 我可以帮助测试这个功能
          required: false
        - label: 我可以提供设计/文案支持
          required: false
